/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.muspellheim.kanbanboard.backend

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
