/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.muspellheim.kanbanboard

import kotlin.test.Ignore
import kotlin.test.Test
import kotlin.test.assertNotNull

@Ignore
class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
